HOST_OS:=FreeBSD
HOST_ARCH:=amd64
GNU_HOST_NAME:=x86_64-unknown-freebsd10.0
TAR:=/usr/bin/tar
FIND:=/usr/bin/find
BASH:=/bin/bash
FIND_L=/usr/bin/find -L $(1)
XARGS:=xargs
PATCH:=/usr/local/bin/gpatch
